import { defineToolcraft } from "@/toolcraft/runtime";

type ClipMotionEasingPoint = { x: number; y: number };

function createClipMotionEasingPreset(points: ClipMotionEasingPoint[]) {
  const clonePoints = () => points.map(({ x, y }) => ({ x, y }));
  return {
    activeChannel: "RGB" as const,
    points: {
      B: clonePoints(),
      G: clonePoints(),
      R: clonePoints(),
      RGB: clonePoints(),
    },
  };
}

export const clipSandboxMotionEasingPresets = {
  linear: createClipMotionEasingPreset([
    { x: 0, y: 0 },
    { x: 0.5, y: 0.5 },
    { x: 1, y: 1 },
  ]),
  easeIn: createClipMotionEasingPreset([
    { x: 0, y: 0 },
    { x: 0.6, y: 0.2 },
    { x: 1, y: 1 },
  ]),
  easeOut: createClipMotionEasingPreset([
    { x: 0, y: 0 },
    { x: 0.4, y: 0.8 },
    { x: 1, y: 1 },
  ]),
  easeInOut: createClipMotionEasingPreset([
    { x: 0, y: 0 },
    { x: 0.25, y: 0.1 },
    { x: 0.75, y: 0.9 },
    { x: 1, y: 1 },
  ]),
};

export const clipLabSandboxControlSectionInventory = [
  { entity: "Source image", groupingReason: "Toolcraft owns upload, attached-file actions, and source transforms as the image stage feeding the invisible mask.", targets: ["clip.source"], title: "Image" },
  { entity: "Threshold source mask", groupingReason: "Threshold converts the runtime-owned source image into the invisible binary clipping mask.", targets: ["clip.threshold"], title: "Source Mask" },
  { entity: "Field focus", groupingReason: "Toolcraft promotes the direct-authored two-axis vector into its own Focus section and canvas interaction.", targets: ["clip.focus"], title: "Focus" },
  { entity: "Radial ray field", groupingReason: "Field shape, signed curl, count, wiggle, and uniform width jointly define geometry around the authored Focus.", targets: ["clip.fieldShape", "clip.curl", "clip.count", "clip.wiggle", "clip.width"], title: "Ray Field" },
  { entity: "Mask-derived path endpoints", groupingReason: "Edge noise and minimum length jointly control the final paths produced after mask subtraction.", targets: ["clip.edgeNoise", "clip.minLength"], title: "Path Ends" },
  { entity: "Focus-oriented ray color", groupingReason: "One compound gradient defines the color distribution from Focus outward on every ray.", targets: ["clip.gradient"], title: "Ray Gradient" },
  { entity: "Ray halo", groupingReason: "Strength and radius jointly define the blurred light halo beneath the crisp ray field.", targets: ["clip.bloomStrength", "clip.bloomRadius"], title: "Bloom" },
  { entity: "Timeline-driven ray shimmer", groupingReason: "Amount, spatial grouping scale, and temporal speed jointly define deterministic animated luminance noise.", targets: ["clip.noiseAmount", "clip.noiseScale", "clip.noiseSpeed"], title: "Noise" },
  { entity: "Periodic path playback", groupingReason: "Participation, speed, easing presets, editable easing, stagger, overlap, and seed jointly control how finished paths repeat toward Focus during timeline playback without changing the static design.", targets: ["clip.motionActive", "clip.motionSpeed", "clip.motionEasingPresets", "clip.motionEasing", "clip.motionStagger", "clip.motionOverlap", "clip.motionSeed"], title: "Motion" },
  { entity: "Output background", groupingReason: "Include and background color jointly control preview and still-export compositing.", targets: ["export.includeBackground", "clip.background"], title: "Background" },
  { workflowStage: "Still image delivery", groupingReason: "Format and resolution jointly configure downloaded and clipboard raster output while SVG remains native vector geometry.", targets: ["export.image.format", "export.image.resolution"], title: "Image Export" },
  { workflowStage: "Animated delivery", groupingReason: "Format and resolution configure the encoded loop, while sticky delivery can also serialize the same motion as scalable animated SVG.", targets: ["export.video.format", "export.video.resolution"], title: "Video Export" },
] as const;

void clipLabSandboxControlSectionInventory;

export const clipLabSandboxSchema = defineToolcraft({
  canvas: {
    enabled: true,
    size: { width: 1920, height: 1080, unit: "px" },
    sizing: { mode: "editable-output" },
    upload: true,
  },
  panels: {
    controls: {
      title: "Speed Rays Sandbox",
      sections: [
        {
          title: "Source Mask",
          controls: {
            source: {
              type: "fileDrop",
              target: "clip.source",
              label: "Image",
              defaultValue: null,
              assetKind: "image",
              accept: "image/*",
              orderRole: "input",
              performanceRole: "workload",
              performanceReason: "Decoding and threshold-mask generation depend on uploaded source dimensions.",
            },
            threshold: {
              type: "slider",
              target: "clip.threshold",
              label: "Threshold",
              defaultValue: 50,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Keeps source pixels at or above this brightness as the white clipping region.",
              performanceReason: "Rewrites a bounded cached mask without increasing ray count.",
            },
          },
        },
        {
          title: "Ray Field",
          controls: {
            focus: {
              type: "vector",
              target: "clip.focus",
              label: "Focus",
              defaultValue: { x: 0, y: 0 },
              coordinateMode: "screen",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Sets the shared point every line aims toward and where its gradient begins.",
              performanceReason: "Moves the bounded ray field without changing primitive count.",
            },
            fieldShape: {
              type: "select",
              target: "clip.fieldShape",
              label: "Shape",
              defaultValue: "straight",
              options: [
                { label: "Straight", value: "straight" },
                { label: "Whirlpool", value: "whirlpool" },
                { label: "Sweep", value: "sweep" },
                { label: "Wave", value: "wave" },
              ],
              orderRole: "mode",
              performanceRole: "responsiveness",
              description: "Changes the base field before the source mask cuts it into final paths.",
              performanceReason: "Changes bounded point geometry for the existing ray count.",
            },
            curl: {
              type: "slider",
              target: "clip.curl",
              label: "Curl",
              defaultValue: 45,
              min: -100,
              max: 100,
              step: 1,
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Controls bend strength and direction for the selected non-straight field.",
              performanceReason: "Recomputes bounded curved path points without changing ray count.",
              visibleWhen: { target: "clip.fieldShape", notEquals: "straight" },
            },
            count: {
              type: "slider",
              target: "clip.count",
              label: "Count",
              defaultValue: 320,
              min: 32,
              max: 1200,
              step: 16,
              orderRole: "detail",
              performanceRole: "workload",
              performanceReason: "Directly changes the number of stroked gradient rays.",
            },
            wiggle: {
              type: "slider",
              target: "clip.wiggle",
              label: "Wiggle",
              defaultValue: 0,
              min: 0,
              max: 80,
              step: 1,
              unit: "px",
              orderRole: "detail",
              performanceRole: "responsiveness",
              performanceReason: "Changes a fixed ten-point path per ray without increasing ray count.",
            },
            width: {
              type: "slider",
              target: "clip.width",
              label: "Width",
              defaultValue: 1,
              min: 0.5,
              max: 100,
              step: 0.1,
              unit: "px",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Sets the crisp ray core width; the sandbox supports extreme poster-scale strokes.",
              performanceReason: "Updates one uniform stroke width across the existing rays and its optional bloom duplicate.",
            },
          },
        },
        {
          title: "Path Ends",
          controls: {
            edgeNoise: {
              type: "slider",
              target: "clip.edgeNoise",
              label: "Edge noise",
              defaultValue: 0,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Randomly lengthens or shortens both ends of every final path along its existing field curve.",
              performanceReason: "Recomputes deterministic segment endpoints without changing the ray or mask sampling count.",
            },
            minLength: {
              type: "slider",
              target: "clip.minLength",
              label: "Min length",
              defaultValue: 12,
              min: 0,
              max: 200,
              step: 1,
              unit: "px",
              orderRole: "detail",
              performanceRole: "workload",
              description: "Hides final mask-derived paths shorter than this output-space length.",
              performanceReason: "Changes how many extracted SVG paths and per-path gradients are retained.",
            },
          },
        },
        {
          title: "Ray Gradient",
          controls: {
            gradient: {
              type: "gradient",
              target: "clip.gradient",
              label: "Ray gradient",
              defaultValue: {
                angle: 0,
                gradientType: "linear",
                stops: [
                  { color: "#FFFFFF", opacity: 100, position: "0%" },
                  { color: "#8CB7FF", opacity: 100, position: "28%" },
                  { color: "#2C69D1", opacity: 100, position: "100%" },
                ],
              },
              orderRole: "color",
              performanceRole: "responsiveness",
              description: "Applies independently from Focus outward along every ray.",
              performanceReason: "Updates bounded per-ray gradient stops without changing geometry.",
            },
          },
        },
        {
          title: "Bloom",
          controls: {
            strength: {
              type: "slider",
              target: "clip.bloomStrength",
              label: "Strength",
              defaultValue: 35,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Adds a luminous blurred copy beneath the crisp rays.",
              performanceReason: "Changes one bounded duplicate path group without rebuilding geometry.",
            },
            radius: {
              type: "slider",
              target: "clip.bloomRadius",
              label: "Radius",
              defaultValue: 18,
              min: 0,
              max: 80,
              step: 1,
              unit: "px",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Controls how far the bloom halo spreads from each ray.",
              performanceReason: "Updates the SVG blur filter or Canvas 2D shadow radius without rebuilding geometry.",
            },
          },
        },
        {
          title: "Noise",
          controls: {
            amount: {
              type: "slider",
              target: "clip.noiseAmount",
              label: "Amount",
              defaultValue: 20,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Modulates ray luminance with deterministic timeline-driven shimmer.",
              performanceReason: "Changes per-path opacity only; mask and geometry remain cached.",
            },
            scale: {
              type: "slider",
              target: "clip.noiseScale",
              label: "Scale",
              defaultValue: 12,
              min: 1,
              max: 64,
              step: 1,
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Controls how broadly neighboring rays share the same shimmer band.",
              performanceReason: "Changes the deterministic noise lookup without increasing path count.",
            },
            speed: {
              type: "slider",
              target: "clip.noiseSpeed",
              label: "Speed",
              defaultValue: 4,
              min: 0,
              max: 20,
              step: 0.5,
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Sets how many shimmer changes occur during one timeline loop.",
              performanceReason: "Updates only the timeline phase used by the deterministic noise lookup.",
            },
          },
        },
        {
          title: "Motion",
          layout: "standalone",
          controls: {
            active: {
              type: "slider",
              target: "clip.motionActive",
              label: "Animated paths",
              defaultValue: 65,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "workload",
              description: "Chooses the deterministic share of finished paths that receive moving replacement copies.",
              performanceReason: "Directly changes how many duplicated SVG path nodes animate during playback.",
            },
            speed: {
              type: "slider",
              target: "clip.motionSpeed",
              label: "Speed",
              defaultValue: 1,
              min: 1,
              max: 100,
              step: 1,
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Runs this many complete replacement cycles during one timeline loop, up to the sandbox lightspeed limit.",
              performanceReason: "Updates only the bounded playback phase multiplier without changing path count or geometry.",
            },
            easingPresets: {
              type: "actions",
              target: "clip.motionEasingPresets",
              label: "Easing presets",
              defaultValue: null,
              actions: [
                { label: "Linear", value: "easing-preset-linear" },
                { label: "Ease in", value: "easing-preset-in" },
                { label: "Ease out", value: "easing-preset-out" },
                { label: "Ease in-out", value: "easing-preset-in-out" },
              ],
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Replaces the editable curve below; you can fine-tune its points afterward.",
              performanceReason: "Writes one bounded easing-curve value without changing path count or geometry.",
            },
            easing: {
              type: "curves",
              target: "clip.motionEasing",
              label: "Easing",
              variant: "single",
              interpolation: "smooth",
              defaultValue: clipSandboxMotionEasingPresets.linear,
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Maps time to travel inside every replacement cycle; the diagonal is linear.",
              performanceReason: "Remaps only normalized motion phase without changing path count or geometry.",
            },
            stagger: {
              type: "slider",
              target: "clip.motionStagger",
              label: "Stagger",
              defaultValue: 70,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Spreads participating paths across the loop instead of moving them all at once.",
              performanceReason: "Updates only deterministic per-path phase offsets.",
            },
            overlap: {
              type: "slider",
              target: "clip.motionOverlap",
              label: "Overlap",
              defaultValue: 0,
              min: 0,
              max: 70,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "workload",
              description: "Shortens the repeat distance so multiple trails can overlap while travelling along long paths.",
              performanceReason: "Raises the bounded number of periodic SVG copies that can intersect each visible path.",
            },
            seed: {
              type: "slider",
              target: "clip.motionSeed",
              label: "Seed",
              defaultValue: 1,
              min: 1,
              max: 100,
              step: 1,
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Changes which paths participate and their stagger order without changing static geometry.",
              performanceReason: "Reassigns bounded deterministic motion metadata for the existing paths.",
            },
          },
        },
        {
          title: "Background",
          controls: {
            include: {
              type: "switch",
              target: "export.includeBackground",
              label: "Include",
              defaultValue: true,
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Controls preview and still-export background compositing.",
            },
            color: {
              type: "color",
              target: "clip.background",
              label: false,
              defaultValue: "#05070B",
              orderRole: "color",
              performanceRole: "responsiveness",
              performanceReason: "Updates only the product background fill.",
            },
          },
          layoutGroups: [{ layout: "inline", columns: 2, controls: ["include", "color"] }],
        },
        {
          title: "Image Export",
          controls: {
            format: {
              type: "select",
              target: "export.image.format",
              label: "Format",
              defaultValue: "png",
              options: [{ label: "PNG", value: "png" }, { label: "JPG", value: "jpg" }],
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Changes only the final still-image encoder.",
            },
            resolution: {
              type: "select",
              target: "export.image.resolution",
              label: "Resolution",
              defaultValue: "4k",
              options: [{ label: "2K", value: "2k" }, { label: "4K", value: "4k" }, { label: "8K", value: "8k" }],
              orderRole: "mode",
              performanceRole: "workload",
              performanceReason: "Changes still-image pixel dimensions and rasterization workload.",
            },
          },
          layoutGroups: [{ layout: "inline", columns: 2, controls: ["format", "resolution"] }],
        },
        {
          title: "Video Export",
          controls: {
            format: {
              type: "select",
              target: "export.video.format",
              label: "Format",
              defaultValue: "mp4",
              options: [{ label: "MP4", value: "mp4" }, { label: "WebM", value: "webm" }],
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Changes only the preferred video encoder family.",
            },
            resolution: {
              type: "select",
              target: "export.video.resolution",
              label: "Resolution",
              defaultValue: "current",
              options: [{ label: "Current", value: "current" }, { label: "2×", value: "2x" }, { label: "4K", value: "4k" }],
              orderRole: "mode",
              performanceRole: "workload",
              description: "Current uses the canvas size, 2× doubles it, and 4K fits it inside 3840×2160.",
              performanceReason: "Changes video frame dimensions and per-frame replay workload.",
            },
          },
          layoutGroups: [{ layout: "inline", columns: 2, controls: ["format", "resolution"] }],
        },
        {
          title: "Export",
          actionGroup: "primary",
          controls: {
            delivery: {
              type: "panelActions",
              target: "clip.sandboxActions",
              defaultValue: null,
              actions: [
                { icon: "upload-simple", label: "Export Video", value: "export-sandbox-video" },
                { icon: "upload-simple", label: "Export Animated SVG", value: "export-sandbox-animated-svg" },
                { icon: "upload-simple", label: "Export PNG", value: "export-sandbox-png" },
                { icon: "copy", label: "Copy PNG", value: "copy-sandbox-png" },
                { icon: "copy", label: "Copy SVG", value: "copy-sandbox-svg" },
              ],
              performanceRole: "workload",
              performanceReason: "Serializes, rasterizes, or records the selected full-resolution clipped ray field for delivery.",
            },
          },
        },
      ],
    },
    timeline: { enabled: true, mode: "playback", defaultDurationSeconds: 6 },
  },
  persistence: { storage: "none" },
  settingsTransfer: "auto",
  toolbar: { history: true, radar: true, theme: true, zoom: true },
});
