import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
  type ToolcraftPerformanceInteraction,
  type ToolcraftPerformanceValueSet,
} from "@/toolcraft/runtime";

const commonBudget = { maxFrameGapMs: 120, maxInteractionMs: 1600, maxLongTaskMs: 180 } as const;

const smoothBaseline = {
  kind: "custom",
  reason: "The measured smooth target keeps the full-HD source and maximum blur at 112 rays with the default motion participation; higher combined density settings remain available as experimental preview states.",
  value: { count: 112, motionActive: 65, overlap: 0, sourceMedia: { height: 1080, width: 1920 }, strength: 100 },
  loadProfile: {
    hardLimit: { count: 1200, height: 1080, motionActive: 100, overlap: 70, renderScale: 2, strength: 100, width: 1920 },
    metric: "custom",
    smoothTarget: { count: 112, motionActive: 65, overlap: 0, sourceMedia: { height: 1080, width: 1920 }, strength: 100 },
    smoothTargetRatio: 0.9,
    target: "mix.preview",
    degradationStepPercent: 10,
    evidence: [{
      attemptedTarget: { count: 1200, height: 1080, motionActive: 100, overlap: 70, renderScale: 2, strength: 100, width: 1920 },
      decision: "Keep the high-density combinations available for experimentation, but guarantee playback at the measured 112-ray full-HD workload.",
      measuredResult: "The combined hard limit produced a 441.5ms maximum frame gap; 320 rays produced 137.5–143.5ms, 240 rays produced 133.1ms, and 160 rays produced 127.4ms against the 120ms budget after the preview-scale correction.",
      optimizationAttempted: "Matched Speed Blur's live Resolution scale 1 default, coalesced live drawing to the 30fps video cadence, and used a 75% intermediate ray texture before the full-size WebGL composite; raster delivery stays full resolution.",
      result: "failed",
      scenarioId: "animation frames stay under budget",
    }],
    userFacingRange: "experimental-above-smooth",
  },
} as const;

const fullHdMedia = {
  kind: "media",
  reason: "A full-HD threshold mask is the practical heavy source for the dense mixed raster pipeline.",
  value: { height: 1080, width: 1920 },
  loadProfile: {
    hardLimit: { height: 1080, width: 1920 },
    metric: "media-area",
    smoothTarget: { height: 1080, width: 1920 },
    smoothTargetRatio: 1,
    target: "clip.source",
    userFacingRange: "fully-guaranteed",
  },
} as const;

function responsive(
  id: string,
  target: string,
  label: string,
  interaction: "control-change" | "control-drag" = "control-change",
) {
  return {
    automated: true,
    automatedTestName: `perf: Mix ${target} remains responsive`,
    browser: true,
    browserTestName: `browser perf: Mix ${target} remains responsive`,
    budget: commonBudget,
    controlLabel: label,
    expectedObservable: `${label} updates final Mix pixels without moving the canvas viewport or rebuilding unrelated upstream passes.`,
    fixture: "Full-HD curved mask with the default 320-ray field and Blur enabled.",
    id,
    interaction,
    target,
    workload: false,
  } as const;
}

function workload(
  id: string,
  target: string,
  label: string,
  interaction: "control-change" | "control-drag" | "export-copy",
  values: ToolcraftPerformanceValueSet,
  stressValue: unknown,
) {
  return {
    automated: true,
    automatedTestName: `perf: Mix ${target} workload is covered`,
    browser: true,
    browserTestName: `browser perf: Mix ${target} workload is covered`,
    budget: interaction === "export-copy" ? { maxExportMs: 8_000 } : commonBudget,
    controlLabel: label,
    expectedObservable: `${label} reaches its heavy exposed value while the complete ray-to-WebGL pipeline remains usable.`,
    fixture: "Maximum full-HD Mix preview with final raster delivery available.",
    id,
    interaction,
    stressFixture: {
      kind: "max-value",
      reason: `${String(stressValue)} is the heaviest exposed ${label} value for this Mix path.`,
      value: stressValue,
      loadProfile: {
        hardLimit: stressValue,
        metric: "custom",
        smoothTarget: stressValue,
        smoothTargetRatio: 1,
        target,
        userFacingRange: "fully-guaranteed",
      },
    },
    target,
    values,
    workload: true,
    workloadFixture: smoothBaseline,
  } as const;
}

function stressScenario(
  id: string,
  interaction: ToolcraftPerformanceInteraction,
  browserTestName: string,
  expectedObservable: string,
  extra: Record<string, unknown> = {},
) {
  return {
    automated: true,
    automatedTestName: `perf: Mix ${id}`,
    browser: true,
    browserTestName,
    budget: interaction === "preview-render"
      ? { maxLongTaskMs: 180, maxPreviewMs: 2000 }
      : interaction === "export-copy"
        ? { maxExportMs: 8_000 }
        : { maxFrameGapMs: 120, maxInteractionMs: 1800, maxLongTaskMs: 180 },
    expectedObservable,
    fixture: "Measured full-HD smooth target with maximum Blur Motion and the default Speed Rays workload.",
    id,
    interaction,
    stress: true,
    stressFixture: smoothBaseline,
    workload: false,
    ...extra,
  };
}

export const mixPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    preferredRunner: "agent-browser",
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
  },
  rendererStrategy: "webgl",
  rendererWorkload: "pixel-output",
  rendererTechnique: {
    sourceRepresentation: "mixed",
    productRepresentation: "pixel",
    previewRenderer: "webgl",
    exportRenderer: "webcodecs",
    rendererWorkload: "pixel-output",
    rendererStrategy: "webgl",
    intentionalRasterizationReason: "Mix intentionally rasterizes Speed Rays because the final Speed Blur radial exposure is a pixel-sampling effect and the user excluded SVG output.",
    previewExportDifferenceReason: "Live preview uses a 75% intermediate ray texture and the full selected canvas backing for the WebGL composite; still/video delivery replays both passes at the exact selected export dimensions and deterministic frame timestamps.",
    fidelityRisks: ["The live intermediate texture is intentionally reduced before radial exposure for responsive playback; final output remains full-resolution and uses the same gradients, stroke width, motion windows, and blur shader."],
    performanceRisks: ["Maximum ray overlap plus a 2× full-HD backing requires a Canvas 2D redraw and GPU texture upload per playback frame; 8K still and 4K video remain export-only workloads."],
    whyNotAlternativeStrategies: [
      "Native SVG cannot represent the final radial pixel-sampling exposure required by Speed Blur.",
      "Canvas 2D alone would require CPU pixel resampling for the blur, so the radial exposure remains a single WebGL fragment pass.",
      "WebGL-only ray construction would replace the accepted mask-derived path and gradient model and make exact Speed Rays behavior harder to preserve.",
    ],
    layers: [
      { id: "background", kind: "background", renderer: "webgl", primitiveCount: "low", content: ["composite"], exportMode: "composited", uiSelector: "[data-toolcraft-product-output]" },
      { id: "rays", kind: "product-foreground", renderer: "canvas-2d", primitiveCount: "high", content: ["geometry", "dense-pattern"], exportMode: "included", uiSelector: "[data-toolcraft-product-output]" },
      { id: "blur", kind: "product-foreground", renderer: "webgl", primitiveCount: "high", content: ["shader", "composite"], exportMode: "included", uiSelector: "[data-toolcraft-product-output]" },
      { id: "focus-handle", kind: "editing-handles", renderer: "dom", primitiveCount: "low", content: ["geometry"], exportMode: "excluded", uiSelector: "[data-mix-focus-handle]" },
      { id: "delivery", kind: "export-composite", renderer: "webgl", primitiveCount: "high", content: ["geometry", "shader", "composite"], exportMode: "composited", intentionalRasterizationReason: "Raster and video actions replay the Canvas 2D ray pass through the final WebGL composite at the requested dimensions." },
    ],
  },
  rendererPipeline: {
    passes: [
      { id: "source-decode", kind: "decode", runsOn: "main", output: "source", quality: "full", inputs: ["clip.source", "mediaAssets[].transform"], invalidatedBy: ["clip.source", "mediaAssets[].transform"], cacheKey: ["clip.source.dataUrl", "mediaAssets[].transform"] },
      { id: "threshold-mask", kind: "pixel-transform", runsOn: "gpu", output: "intermediate", quality: "preview", inputs: ["source-decode", "clip.threshold", "canvas.size"], invalidatedBy: ["source-decode", "clip.threshold", "canvas.size"], cacheKey: ["clip.source.dataUrl", "clip.threshold", "canvas.size"] },
      { id: "ray-geometry", kind: "vector-build", runsOn: "main", output: "intermediate", quality: "full", inputs: ["threshold-mask", "clip.focus", "clip.fieldShape", "clip.curl", "clip.count", "clip.wiggle", "clip.edgeNoise", "clip.minLength"], invalidatedBy: ["threshold-mask", "clip.focus", "clip.fieldShape", "clip.curl", "clip.count", "clip.wiggle", "clip.edgeNoise", "clip.minLength"], cacheKey: ["threshold-mask", "clip.focus", "clip.fieldShape", "clip.curl", "clip.count", "clip.wiggle", "clip.edgeNoise", "clip.minLength"] },
      { id: "ray-frame", kind: "composite", runsOn: "main", output: "intermediate", quality: "preview", inputs: ["ray-geometry", "clip.width", "clip.gradient", "clip.motionActive", "clip.motionSpeed", "clip.motionEasing", "clip.motionStagger", "clip.motionOverlap", "clip.motionSeed", "timeline.playback", "canvas.renderScale"], invalidatedBy: ["ray-geometry", "clip.width", "clip.gradient", "clip.motionActive", "clip.motionSpeed", "clip.motionEasing", "clip.motionStagger", "clip.motionOverlap", "clip.motionSeed", "timeline.playback", "canvas.renderScale"], cacheKey: ["ray-geometry", "clip.gradient", "clip.motionActive", "clip.motionStagger", "clip.motionOverlap", "clip.motionSeed"] },
      { id: "radial-blur", kind: "composite", runsOn: "gpu", output: "preview", quality: "retina", inputs: ["ray-frame", "clip.focus", "mix.blur.strength", "mix.blur.softness", "mix.blur.falloff", "mix.blur.blend", "clip.background", "export.includeBackground"], invalidatedBy: ["ray-frame", "clip.focus", "mix.blur.strength", "mix.blur.softness", "mix.blur.falloff", "mix.blur.blend", "clip.background", "export.includeBackground"], cacheKey: ["ray-frame"] },
      { id: "focus-handle", kind: "composite", runsOn: "main", output: "overlay", quality: "full", inputs: ["clip.focus"], invalidatedBy: ["clip.focus"], cacheKey: ["clip.focus"] },
      { id: "still-export", kind: "export", runsOn: "export-only", output: "export", quality: "export", inputs: ["ray-frame", "radial-blur", "export.image.format", "export.image.resolution", "mix.exportAction"], invalidatedBy: ["radial-blur", "export.image.format", "export.image.resolution", "mix.exportAction"], cacheKey: ["ray-geometry", "clip.gradient", "timeline.playback", "blur-settings"] },
      { id: "video-export", kind: "export", runsOn: "export-only", output: "export", quality: "export", inputs: ["ray-frame", "radial-blur", "export.video.format", "export.video.resolution", "mix.exportAction"], invalidatedBy: ["radial-blur", "export.video.format", "export.video.resolution", "mix.exportAction"], cacheKey: ["ray-geometry", "clip.gradient", "motion-settings", "blur-settings"] },
    ],
    interactionInvalidation: [
      { interaction: "media-import", targets: ["clip.source"], invalidates: ["source-decode", "threshold-mask", "ray-geometry", "ray-frame", "radial-blur"], mustNotInvalidate: ["still-export", "video-export"] },
      { interaction: "control-drag", targets: ["clip.threshold", "clip.curl", "clip.count", "clip.wiggle", "clip.width", "clip.edgeNoise", "clip.minLength", "clip.motionActive", "clip.motionSpeed", "clip.motionStagger", "clip.motionOverlap", "clip.motionSeed", "mix.blur.strength", "mix.blur.softness", "mix.blur.falloff", "mix.blur.blend"], invalidates: ["ray-geometry", "ray-frame", "radial-blur"], mustNotInvalidate: ["source-decode", "still-export", "video-export"] },
      { interaction: "control-change", targets: ["clip.focus", "clip.fieldShape", "clip.gradient", "clip.motionEasingPresets", "clip.motionEasing", "export.includeBackground", "clip.background", "export.image.format", "export.image.resolution", "export.video.format", "export.video.resolution"], invalidates: ["ray-frame", "radial-blur", "focus-handle"], mustNotInvalidate: ["source-decode"] },
      { interaction: "mask-drag", targets: ["clip.focus"], invalidates: ["ray-geometry", "ray-frame", "radial-blur", "focus-handle"], mustNotInvalidate: ["source-decode", "still-export", "video-export"] },
      { interaction: "animation-frame", targets: ["timeline.playback"], invalidates: ["ray-frame", "radial-blur"], mustNotInvalidate: ["source-decode", "threshold-mask", "ray-geometry"] },
      { interaction: "timeline-playback", targets: ["timeline.playback"], invalidates: ["ray-frame", "radial-blur"], mustNotInvalidate: ["source-decode", "threshold-mask", "ray-geometry"] },
      { interaction: "viewport-drag", targets: ["canvas.viewport"], invalidates: [], mustNotInvalidate: ["source-decode", "threshold-mask", "ray-geometry", "ray-frame", "radial-blur"] },
      { interaction: "viewport-zoom", targets: ["canvas.zoom"], invalidates: [], mustNotInvalidate: ["source-decode", "threshold-mask", "ray-geometry", "ray-frame", "radial-blur"] },
      { interaction: "export", targets: ["export.image.resolution", "export.video.resolution", "mix.exportAction"], invalidates: ["still-export", "video-export"], mustNotInvalidate: ["source-decode", "threshold-mask", "ray-geometry"] },
    ],
  },
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: Mix source media import is covered",
      browser: true,
      browserTestName: "browser perf: Mix source media import is covered",
      budget: commonBudget,
      controlLabel: "Image",
      expectedObservable: "A full-HD mask decodes, thresholds, builds rays, and reaches the WebGL output without changing the viewport.",
      fixture: "1920×1080 high-contrast mask.",
      id: "source-import",
      interaction: "media-import",
      stressFixture: fullHdMedia,
      target: "clip.source",
      workload: true,
    },
    {
      ...workload("source-values", "clip.source", "Image", "control-change", { min: null, default: null, max: { height: 1080, width: 1920 } }, { height: 1080, width: 1920 }),
      stressFixture: fullHdMedia,
    },
    workload("ray-count", "clip.count", "Count", "control-drag", { min: 32, default: 320, max: 1200 }, 1200),
    workload("minimum-length", "clip.minLength", "Min length", "control-drag", { min: 0, default: 12, max: 200 }, 0),
    workload("motion-active", "clip.motionActive", "Animated paths", "control-drag", { min: 0, default: 65, max: 100 }, 100),
    workload("motion-overlap", "clip.motionOverlap", "Overlap", "control-drag", { min: 0, default: 0, max: 70 }, 70),
    workload("image-resolution", "export.image.resolution", "Image resolution", "control-change", { min: "2k", default: "4k", max: "8k" }, "8k"),
    workload("video-resolution", "export.video.resolution", "Video resolution", "control-change", { min: "current", default: "current", max: "4k" }, "4k"),
    workload("delivery-actions", "mix.exportAction", "Delivery", "control-change", { min: "copy-mix-png", default: "export-mix-png", max: "export-mix-video" }, "export-mix-video"),
    responsive("threshold", "clip.threshold", "Threshold", "control-drag"),
    responsive("focus", "clip.focus", "Focus"),
    responsive("shape", "clip.fieldShape", "Shape"),
    responsive("curl", "clip.curl", "Curl", "control-drag"),
    responsive("wiggle", "clip.wiggle", "Wiggle", "control-drag"),
    responsive("width", "clip.width", "Width", "control-drag"),
    responsive("edge-noise", "clip.edgeNoise", "Edge noise", "control-drag"),
    responsive("gradient", "clip.gradient", "Ray gradient"),
    responsive("blur-strength", "mix.blur.strength", "Motion", "control-drag"),
    responsive("blur-softness", "mix.blur.softness", "Exposure", "control-drag"),
    responsive("blur-falloff", "mix.blur.falloff", "Focus area", "control-drag"),
    responsive("blur-blend", "mix.blur.blend", "Blend", "control-drag"),
    responsive("motion-speed", "clip.motionSpeed", "Speed", "control-drag"),
    responsive("motion-presets", "clip.motionEasingPresets", "Easing presets"),
    responsive("motion-easing", "clip.motionEasing", "Easing"),
    responsive("motion-stagger", "clip.motionStagger", "Stagger", "control-drag"),
    responsive("motion-seed", "clip.motionSeed", "Seed", "control-drag"),
    responsive("background-include", "export.includeBackground", "Include"),
    responsive("background-color", "clip.background", "Background"),
    responsive("image-format", "export.image.format", "Image format"),
    responsive("video-format", "export.video.format", "Video format"),
    stressScenario("smooth-target preview stays under budget", "preview-render", "browser perf: Mix renders smooth-target rays and blur at full-HD", "The measured full-HD ray frame and maximum radial exposure reach the visible WebGL output.", { uiSelector: "[data-toolcraft-product-output]" }),
    stressScenario("animation frames stay under budget", "animation-frame", "browser perf: Mix animation frames stay under budget", "Maximum periodic overlap advances through the same GPU post-process without rebuilding the mask."),
    stressScenario("animation viewport drag stays stable", "animation-viewport-drag", "browser perf: Mix animation viewport drag stays stable", "Dragging the viewport during playback coalesces non-essential frame work without changing playback state.", { target: "canvas.viewport" }),
    stressScenario("viewport zoom stays stable", "viewport-zoom-stress", "browser perf: Mix viewport zoom stays stable", "Toolbar zoom preserves the selected output backing and the responsive preview cadence.", { target: "canvas.zoom" }),
    {
      automated: true,
      automatedTestName: "perf: Mix viewport state stays stable",
      browser: true,
      browserTestName: "browser perf: Mix viewport state stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable: "Mix controls preserve canvas zoom and offset.",
      fixture: "Default Mix output at an authored zoom and offset.",
      id: "viewport-stability",
      interaction: "viewport-stability",
      target: "canvas.viewport",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Mix timeline playback stays under budget",
      browser: true,
      browserTestName: "browser perf: Mix timeline playback stays under budget",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 180 },
      controlLabel: "Play playback",
      expectedObservable: "The smooth-target blurred trail train advances through the Toolcraft timeline with a seamless forward loop.",
      fixture: "Measured smooth-target full-HD Mix state.",
      id: "timeline-playback",
      interaction: "timeline-playback",
      target: "timeline.playback",
      workload: false,
    },
    stressScenario("raster export stays under budget", "export-copy", "browser perf: Mix raster export stays under budget", "The two-stage renderer produces selected-resolution still or video bytes with progress.", { target: "mix.exportAction" }),
  ],
  usesCustomRenderer: true,
  workloadTargets: ["clip.source", "clip.count", "clip.minLength", "clip.motionActive", "clip.motionOverlap", "export.image.resolution", "export.video.resolution", "mix.exportAction"],
});
