import { defineToolcraftPerformance, type ToolcraftPerformanceConfig } from "@/toolcraft/runtime";

const commonBudget = { maxFrameGapMs: 120, maxInteractionMs: 1200, maxLongTaskMs: 180 } as const;
const fourKMedia = {
  kind: "media",
  reason: "A 3840×2160 photo is the realistic high-resolution source for the per-pixel paper shader.",
  value: { height: 2160, width: 3840 },
  loadProfile: {
    hardLimit: { height: 2160, width: 3840 },
    metric: "media-area",
    smoothTarget: { height: 2160, width: 3840 },
    smoothTargetRatio: 1,
    target: "paper.sources",
    userFacingRange: "fully-guaranteed",
  },
} as const;
const fullBatch = {
  kind: "many-items",
  minCount: 40,
  reason: "Forty images is the product batch limit and the heaviest supported serial export set.",
  value: 40,
  loadProfile: {
    hardLimit: 40,
    metric: "count",
    smoothTarget: 40,
    smoothTargetRatio: 1,
    target: "paper.exportAction",
    userFacingRange: "fully-guaranteed",
  },
} as const;

function responsive(id: string, target: string, controlLabel: string, interaction: "control-change" | "control-drag" = "control-change") {
  return {
    automated: true,
    automatedTestName: `perf: ${target} remains responsive`,
    browser: true,
    browserTestName: `browser perf: ${target} remains responsive`,
    budget: commonBudget,
    controlLabel,
    expectedObservable: `${controlLabel} updates paper-textured GPU pixels without re-decoding the source or moving the viewport.`,
    fixture: "4K photographic source at Resolution scale 2.",
    id,
    interaction,
    target,
    workload: false,
  } as const;
}

export const paperTexturePerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    preferredRunner: "agent-browser",
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
  },
  rendererStrategy: "webgl",
  rendererWorkload: "pixel-output",
  rendererTechnique: {
    sourceRepresentation: "image-media",
    productRepresentation: "pixel",
    previewRenderer: "webgl",
    exportRenderer: "webgl",
    rendererWorkload: "pixel-output",
    rendererStrategy: "webgl",
    fidelityRisks: ["Very small dot spacing can alias at low zoom; selected backing scale and full-resolution export preserve the authored pattern."],
    performanceRisks: ["A 40-image 8K batch can consume substantial encoding time and ZIP memory even though images are processed serially."],
    whyNotAlternativeStrategies: [
      "Canvas 2D CPU pixel loops multiply full-resolution work by every image in the batch.",
      "SVG and DOM cannot apply photographic halftone and fiber patterns to arbitrary image pixels.",
      "WebGPU adds compatibility cost without improving this single-texture, single-pass bounded fragment workload enough to justify a second path.",
    ],
    layers: [
      { id: "background", kind: "background", renderer: "webgl", primitiveCount: "low", content: ["composite"], exportMode: "composited", uiSelector: "[data-toolcraft-product-output]" },
      { id: "paper-image", kind: "product-foreground", renderer: "webgl", primitiveCount: "high", content: ["bitmap-media", "shader", "dense-pattern"], exportMode: "included", uiSelector: "[data-toolcraft-product-output]" },
      { id: "still-batch", kind: "export-composite", renderer: "webgl", primitiveCount: "high", content: ["bitmap-media", "composite"], exportMode: "composited" },
    ],
  },
  rendererPipeline: {
    passes: [
      { id: "source-decode", kind: "decode", runsOn: "main", output: "source", quality: "full", inputs: ["paper.sources", "mediaAssets[].transform"], invalidatedBy: ["paper.sources", "mediaAssets[].transform"], cacheKey: ["paper.sources.dataUrl", "mediaAssets[].transform"] },
      { id: "texture-upload", kind: "preprocess", runsOn: "gpu", output: "intermediate", quality: "full", inputs: ["source-decode"], invalidatedBy: ["source-decode"], cacheKey: ["paper.sources.dataUrl", "mediaAssets[].transform"] },
      { id: "paper-composite", kind: "pixel-transform", runsOn: "gpu", output: "preview", quality: "retina", inputs: ["texture-upload", "paper.style", "paper.amount", "paper.scale", "paper.fade", "paper.background", "export.includeBackground", "canvas.size", "canvas.renderScale"], invalidatedBy: ["texture-upload", "paper.style", "paper.amount", "paper.scale", "paper.fade", "paper.background", "export.includeBackground", "canvas.size", "canvas.renderScale"], cacheKey: ["paper.sources.dataUrl", "mediaAssets[].transform"] },
      { id: "still-export", kind: "export", runsOn: "export-only", output: "export", quality: "export", inputs: ["paper-composite", "export.image.format", "export.image.resolution"], invalidatedBy: ["paper-composite", "export.image.format", "export.image.resolution"], cacheKey: ["paper.sources.dataUrl", "mediaAssets[].transform", "paper.style", "paper.amount", "paper.scale", "paper.fade"] },
      { id: "zip-package", kind: "export", runsOn: "export-only", output: "export", quality: "export", inputs: ["still-export", "paper.exportAction"], invalidatedBy: ["still-export", "paper.exportAction"], cacheKey: ["paper.sources.order", "export.image.format", "export.image.resolution"] },
    ],
    interactionInvalidation: [
      { interaction: "media-import", targets: ["paper.sources"], invalidates: ["source-decode", "texture-upload", "paper-composite"], mustNotInvalidate: ["still-export", "zip-package"] },
      { interaction: "control-drag", targets: ["paper.amount", "paper.scale", "paper.fade"], invalidates: ["paper-composite"], mustNotInvalidate: ["source-decode", "texture-upload", "still-export", "zip-package"] },
      { interaction: "control-change", targets: ["paper.style", "export.includeBackground", "paper.background", "export.image.format", "export.image.resolution"], invalidates: ["paper-composite"], mustNotInvalidate: ["source-decode", "texture-upload"] },
      { interaction: "viewport-drag", targets: ["canvas.viewport"], invalidates: [], mustNotInvalidate: ["source-decode", "texture-upload", "paper-composite"] },
      { interaction: "viewport-zoom", targets: ["canvas.zoom"], invalidates: [], mustNotInvalidate: ["source-decode", "texture-upload", "paper-composite"] },
      { interaction: "export", targets: ["export.image.resolution", "paper.exportAction"], invalidates: ["still-export", "zip-package"], mustNotInvalidate: ["source-decode", "texture-upload"] },
    ],
  },
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: paper source media import is covered",
      browser: true,
      browserTestName: "browser perf: paper source media import is covered",
      budget: commonBudget,
      controlLabel: "Images",
      expectedObservable: "A 4K source decodes, uploads once, and produces the first textured preview.",
      fixture: "3840×2160 photographic source.",
      id: "source-import",
      interaction: "media-import",
      stressFixture: fourKMedia,
      target: "paper.sources",
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: paper.exportAction workload is covered",
      browser: true,
      browserTestName: "browser perf: paper.exportAction workload is covered",
      budget: commonBudget,
      controlLabel: "Export Batch",
      expectedObservable: "The batch action selects the forty-item serial export path without destabilizing the preview viewport.",
      fixture: "Forty ordered image sources.",
      id: "batch-action-values",
      interaction: "control-change",
      stressFixture: { kind: "max-value", reason: "Batch export is the heavier of the two delivery actions.", value: "export-paper-batch", loadProfile: { hardLimit: "export-paper-batch", metric: "custom", smoothTarget: "export-paper-batch", smoothTargetRatio: 1, target: "paper.exportAction", userFacingRange: "fully-guaranteed" } },
      workloadFixture: fullBatch,
      target: "paper.exportAction",
      values: { min: "export-paper-image", default: "export-paper-image", max: "export-paper-batch" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: paper.sources workload is covered",
      browser: true,
      browserTestName: "browser perf: paper.sources workload is covered",
      budget: commonBudget,
      controlLabel: "Images",
      expectedObservable: "The source input reaches a 4K media baseline while preserving the editable canvas viewport.",
      fixture: "3840×2160 photographic source.",
      id: "source-values",
      interaction: "control-change",
      stressFixture: { kind: "max-value", reason: "A 4K source is the maximum declared source control value.", value: { height: 2160, width: 3840 }, loadProfile: { hardLimit: { height: 2160, width: 3840 }, metric: "media-area", smoothTarget: { height: 2160, width: 3840 }, smoothTargetRatio: 1, target: "paper.sources", userFacingRange: "fully-guaranteed" } },
      workloadFixture: fourKMedia,
      target: "paper.sources",
      values: { min: null, default: null, max: { height: 2160, width: 3840 } },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: paper batch action supports forty images",
      browser: true,
      browserTestName: "browser perf: paper batch action supports forty images",
      budget: { maxExportMs: 8000 },
      controlLabel: "Export Batch",
      expectedObservable: "Forty ordered images render serially and package into one ZIP with determinate progress.",
      fixture: "Forty image sources using the shared fine-dot recipe.",
      id: "batch-export",
      interaction: "export-copy",
      stressFixture: fullBatch,
      workloadFixture: fourKMedia,
      target: "paper.exportAction",
      values: { min: "export-paper-image", default: "export-paper-image", max: "export-paper-batch" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: paper image resolution workload is covered",
      browser: true,
      browserTestName: "browser perf: paper image resolution workload is covered",
      budget: commonBudget,
      controlLabel: "Resolution",
      expectedObservable: "The selected 8K long edge is rendered by the same shader without changing preview dimensions.",
      fixture: "4K source with 8K output selected.",
      id: "image-resolution",
      interaction: "control-change",
      stressFixture: { kind: "max-value", reason: "8K is the maximum exposed still resolution.", value: "8k", loadProfile: { hardLimit: "8k", metric: "custom", smoothTarget: "8k", smoothTargetRatio: 1, target: "export.image.resolution", userFacingRange: "fully-guaranteed" } },
      workloadFixture: fourKMedia,
      target: "export.image.resolution",
      values: { min: "2k", default: "4k", max: "8k" },
      workload: true,
    },
    responsive("style", "paper.style", "Style"),
    responsive("amount", "paper.amount", "Amount", "control-drag"),
    {
      automated: true,
      automatedTestName: "perf: paper.scale workload is covered",
      browser: true,
      browserTestName: "browser perf: paper.scale workload is covered",
      budget: commonBudget,
      controlLabel: "Scale",
      expectedObservable: "The live preview reaches the densest 2px texture at the full 4K/2× source baseline.",
      fixture: "4K photographic source at Resolution scale 2.",
      id: "texture-scale",
      interaction: "control-drag",
      stressFixture: { kind: "max-value", reason: "2px is the densest and most alias-sensitive exposed paper spacing.", value: 2, loadProfile: { hardLimit: 2, metric: "numeric-min", smoothTarget: 2, smoothTargetRatio: 1, target: "paper.scale", userFacingRange: "fully-guaranteed" } },
      workloadFixture: fourKMedia,
      target: "paper.scale",
      values: { min: 2, default: 5, max: 16 },
      workload: true,
    },
    responsive("fade", "paper.fade", "Print fade", "control-drag"),
    responsive("background-include", "export.includeBackground", "Include"),
    responsive("background-color", "paper.background", "Background"),
    responsive("image-format", "export.image.format", "Format"),
    {
      automated: true,
      automatedTestName: "perf: maximum Paper Texture preview stays under budget",
      browser: true,
      browserTestName: "browser perf: maximum Paper Texture preview stays under budget",
      budget: { maxLongTaskMs: 180, maxPreviewMs: 1800 },
      expectedObservable: "The 4K/2× fine-dot preview renders in one bounded shader pass.",
      fixture: "4K source, Amount 100, Scale 2, Resolution scale 2.",
      id: "preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: { kind: "custom", reason: "This is the combined worst-case live paper preview.", value: { amount: 100, renderScale: 2, scale: 2, sourceMedia: { height: 2160, width: 3840 } }, loadProfile: { hardLimit: { amount: 100, renderScale: 2, scale: 2, sourceMedia: { height: 2160, width: 3840 } }, metric: "custom", smoothTarget: { amount: 100, renderScale: 2, scale: 2, sourceMedia: { height: 2160, width: 3840 } }, smoothTargetRatio: 1, target: "paper.preview", userFacingRange: "fully-guaranteed" } },
      uiSelector: "[data-toolcraft-product-output]",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Paper Texture viewport zoom stays stable",
      browser: true,
      browserTestName: "browser perf: Paper Texture viewport zoom stays stable",
      budget: commonBudget,
      expectedObservable: "Toolbar zoom preserves the maximum GPU preview and cached source texture.",
      fixture: "Maximum Paper Texture preview state.",
      id: "viewport-zoom",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: { kind: "custom", reason: "Zoom must hold the combined maximum preview state.", value: { amount: 100, renderScale: 2, scale: 2, sourceMedia: { height: 2160, width: 3840 } }, loadProfile: { hardLimit: { amount: 100, renderScale: 2, scale: 2, sourceMedia: { height: 2160, width: 3840 } }, metric: "custom", smoothTarget: { amount: 100, renderScale: 2, scale: 2, sourceMedia: { height: 2160, width: 3840 } }, smoothTargetRatio: 1, target: "canvas.zoom", userFacingRange: "fully-guaranteed" } },
      target: "canvas.zoom",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Paper Texture viewport state stays stable",
      browser: true,
      browserTestName: "browser perf: Paper Texture viewport state stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable: "Texture controls preserve authored canvas zoom and offset.",
      fixture: "Default paper texture at an authored zoom and offset.",
      id: "viewport-stability",
      interaction: "viewport-stability",
      target: "canvas.viewport",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: ["paper.sources", "paper.scale", "export.image.resolution", "paper.exportAction"],
});
