import { defineToolcraft } from "@/toolcraft/runtime";

export const paperTextureControlSectionInventory = [
  {
    entity: "Ordered source images",
    groupingReason: "Upload, runtime-owned transforms, and thumbnail order define the batch source set.",
    targets: ["paper.sources"],
    title: "Source",
  },
  {
    entity: "Printed paper treatment",
    groupingReason: "Style, amount, scale, and fade form one shared recipe applied to every source image.",
    targets: ["paper.style", "paper.amount", "paper.scale", "paper.fade"],
    title: "Paper Texture",
  },
  {
    entity: "Output background",
    groupingReason: "Include and color jointly control preview and still-export compositing.",
    targets: ["export.includeBackground", "paper.background"],
    title: "Background",
  },
  {
    workflowStage: "Still and batch delivery",
    groupingReason: "Format and resolution configure every processed image before delivery.",
    targets: ["export.image.format", "export.image.resolution"],
    title: "Image Export",
  },
] as const;

export const paperTextureSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: { defaultValue: 1, enabled: true, max: 2, min: 1, step: 0.25 },
    size: { height: 1080, unit: "px", width: 1920 },
    sizing: { mode: "editable-output" },
    upload: true,
  },
  panels: {
    controls: {
      title: "Paper Texture Batch",
      sections: [
        {
          title: "Source",
          controls: {
            images: {
              accept: "image/*",
              assetKind: "image",
              defaultValue: null,
              description: "Upload and reorder up to 40 images. The first image is shown on the canvas; the same recipe is applied to the full batch.",
              label: "Images",
              multiple: true,
              orderRole: "input",
              performanceReason: "Source dimensions and batch size determine decode, texture upload, and serial export workload.",
              performanceRole: "workload",
              target: "paper.sources",
              type: "fileDrop",
            },
          },
        },
        {
          title: "Paper Texture",
          controls: {
            style: {
              defaultValue: "fine-dots",
              description: "Chooses a regular fine screen, a coarser offset newsprint screen, or directional paper fibers.",
              label: "Style",
              options: [
                { label: "Fine dots", value: "fine-dots" },
                { label: "Newsprint", value: "newsprint" },
                { label: "Fibers", value: "fibers" },
              ],
              orderRole: "mode",
              performanceReason: "Switches a bounded fragment-shader branch without changing sample count or source decode.",
              performanceRole: "responsiveness",
              target: "paper.style",
              type: "select",
            },
            amount: {
              defaultValue: 28,
              description: "Sets how strongly the paper pattern marks light and dark image areas.",
              label: "Amount",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Updates one shader uniform and must remain live while dragging.",
              performanceRole: "responsiveness",
              step: 1,
              target: "paper.amount",
              type: "slider",
              unit: "%",
            },
            scale: {
              defaultValue: 5,
              description: "Sets the spacing of dots or fibers in final output pixels.",
              label: "Scale",
              max: 16,
              min: 2,
              orderRole: "detail",
              performanceReason: "The smallest spacing produces the densest visible output pattern and must be covered at full preview backing resolution.",
              performanceRole: "workload",
              step: 0.5,
              target: "paper.scale",
              type: "slider",
              unit: "px",
            },
            fade: {
              defaultValue: 8,
              description: "Lifts ink and color toward the paper for a lightly printed finish.",
              label: "Print fade",
              max: 40,
              min: 0,
              orderRole: "detail",
              performanceReason: "Updates one shader uniform and does not rebuild source textures.",
              performanceRole: "responsiveness",
              step: 1,
              target: "paper.fade",
              type: "slider",
              unit: "%",
            },
          },
        },
        {
          title: "Background",
          controls: {
            include: {
              defaultValue: true,
              label: "Include",
              orderRole: "mode",
              performanceReason: "Controls preview and still-export background compositing.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            color: {
              defaultValue: "#F4F1E8",
              label: false,
              orderRole: "color",
              performanceReason: "Updates the paper color shader uniform without decoding the source again.",
              performanceRole: "responsiveness",
              target: "paper.background",
              type: "color",
            },
          },
          layoutGroups: [{ columns: 2, controls: ["include", "color"], layout: "inline" }],
        },
        {
          title: "Image Export",
          controls: {
            format: {
              defaultValue: "png",
              label: "Format",
              options: [{ label: "PNG", value: "png" }, { label: "JPG", value: "jpg" }],
              orderRole: "mode",
              performanceReason: "Changes only final image encoding for single and batch delivery.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            resolution: {
              defaultValue: "4k",
              label: "Resolution",
              options: [{ label: "2K", value: "2k" }, { label: "4K", value: "4k" }, { label: "8K", value: "8k" }],
              orderRole: "mode",
              performanceReason: "Changes final pixel count for every processed image in the batch.",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
            },
          },
          layoutGroups: [{ columns: 2, controls: ["format", "resolution"], layout: "inline" }],
        },
        {
          actionGroup: "primary",
          title: "Export",
          controls: {
            delivery: {
              actions: [
                { icon: "upload-simple", label: "Export PNG", value: "export-paper-image" },
                { icon: "upload-simple", label: "Export Batch", value: "export-paper-batch" },
              ],
              defaultValue: null,
              performanceReason: "Single export renders one full-resolution frame; batch export serially renders and packages up to 40 frames.",
              performanceRole: "workload",
              target: "paper.exportAction",
              type: "panelActions",
            },
          },
        },
      ],
    },
  },
  persistence: { storage: "none" },
  settingsTransfer: "auto",
  toolbar: { history: true, radar: true, theme: true, zoom: true },
});
