import { defineToolcraft } from "@/toolcraft/runtime";

export const warpControlSectionInventory = [
  { entity: "Source image", groupingReason: "Upload and runtime-owned transforms define the photographic input stage.", targets: ["warp.source"], title: "Source" },
  { entity: "Radial origin", groupingReason: "The Vector control and canvas handle edit the same stable convergence point.", targets: ["warp.focus"], title: "Focus" },
  { entity: "Long-exposure zoom burst", groupingReason: "Motion, exposure, focus area, and blend jointly define the continuous photographic streak field.", targets: ["warp.strength", "warp.softness", "warp.falloff", "warp.blend"], title: "Warp" },
  { entity: "Output background", groupingReason: "Include and color jointly control preview and still-export compositing.", targets: ["export.includeBackground", "warp.background"], title: "Background" },
  { workflowStage: "Still image delivery", groupingReason: "Format and resolution configure the final raster output.", targets: ["export.image.format", "export.image.resolution"], title: "Image Export" },
] as const;

export const warpSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: { defaultValue: 1, enabled: true, max: 2, min: 1, step: 0.25 },
    size: { width: 1920, height: 1080, unit: "px" },
    sizing: { mode: "intrinsic-media" },
    upload: true,
  },
  panels: {
    controls: {
      title: "Radial Warp",
      sections: [
        {
          title: "Source",
          controls: {
            image: {
              type: "fileDrop",
              target: "warp.source",
              label: "Image",
              defaultValue: null,
              assetKind: "image",
              accept: "image/*",
              orderRole: "input",
              performanceRole: "workload",
              performanceReason: "Source dimensions determine image decode and GPU texture upload workload.",
            },
          },
        },
        {
          title: "Focus",
          controls: {
            focus: {
              type: "vector",
              target: "warp.focus",
              label: "Position",
              defaultValue: { x: 0, y: 0 },
              coordinateMode: "screen",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Sets the point where detail holds together before stretching into rays.",
              performanceReason: "Updates one shader uniform without decoding or uploading the source again.",
            },
          },
        },
        {
          title: "Warp",
          controls: {
            strength: {
              type: "slider",
              target: "warp.strength",
              label: "Motion",
              defaultValue: 64,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Sets how far the virtual camera travels during the radial exposure.",
              performanceReason: "Updates the fixed exposure path length through one shader uniform.",
            },
            softness: {
              type: "slider",
              target: "warp.softness",
              label: "Exposure",
              defaultValue: 72,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Balances a crisp starting frame with light gathered continuously along the camera move.",
              performanceReason: "Changes weighting and spacing inside the fixed six-sample exposure kernel.",
            },
            falloff: {
              type: "slider",
              target: "warp.falloff",
              label: "Focus area",
              defaultValue: 32,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Sets the readable region held around the focal point before motion streaks build outward.",
              performanceReason: "Updates the preserved radial focus mask through one shader uniform.",
            },
            blend: {
              type: "slider",
              target: "warp.blend",
              label: "Blend",
              defaultValue: 100,
              min: 0,
              max: 100,
              step: 1,
              unit: "%",
              orderRole: "detail",
              performanceRole: "responsiveness",
              description: "Mixes the warp with the original photograph.",
              performanceReason: "Mixes two existing shader colors without changing sample count.",
            },
          },
        },
        {
          title: "Background",
          controls: {
            include: {
              type: "switch",
              target: "export.includeBackground",
              label: "Include",
              defaultValue: true,
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Controls preview and still-export background compositing.",
            },
            color: {
              type: "color",
              target: "warp.background",
              label: false,
              defaultValue: "#05070B",
              orderRole: "color",
              performanceRole: "responsiveness",
              performanceReason: "Updates only the shader background uniform.",
            },
          },
          layoutGroups: [{ layout: "inline", columns: 2, controls: ["include", "color"] }],
        },
        {
          title: "Image Export",
          controls: {
            format: {
              type: "select",
              target: "export.image.format",
              label: "Format",
              defaultValue: "png",
              options: [{ label: "PNG", value: "png" }, { label: "JPG", value: "jpg" }],
              orderRole: "mode",
              performanceRole: "responsiveness",
              performanceReason: "Changes only the final still-image encoder.",
            },
            resolution: {
              type: "select",
              target: "export.image.resolution",
              label: "Resolution",
              defaultValue: "4k",
              options: [{ label: "2K", value: "2k" }, { label: "4K", value: "4k" }, { label: "8K", value: "8k" }],
              orderRole: "mode",
              performanceRole: "workload",
              performanceReason: "Changes final raster dimensions and GPU export workload.",
            },
          },
          layoutGroups: [{ layout: "inline", columns: 2, controls: ["format", "resolution"] }],
        },
        {
          title: "Export",
          actionGroup: "primary",
          controls: {
            delivery: {
              type: "panelActions",
              target: "warp.exportAction",
              defaultValue: null,
              actions: [{ icon: "upload-simple", label: "Export PNG", value: "export-warp-image" }],
              performanceRole: "workload",
              performanceReason: "Renders the full-resolution shader result and encodes the selected image format.",
            },
          },
        },
      ],
    },
  },
  persistence: { storage: "none" },
  settingsTransfer: "auto",
  toolbar: { history: true, radar: true, theme: true, zoom: true },
});
