import { defineToolcraftPerformance, type ToolcraftPerformanceConfig } from "@/toolcraft/runtime";

const commonBudget = { maxFrameGapMs: 120, maxInteractionMs: 1200, maxLongTaskMs: 180 } as const;
const fourKMedia = {
  kind: "media",
  reason: "A 3840×2160 photo at Resolution scale 2 is the realistic high-resolution Warp source baseline.",
  value: { width: 3840, height: 2160 },
  loadProfile: {
    hardLimit: { width: 3840, height: 2160 },
    metric: "media-area",
    smoothTarget: { width: 3840, height: 2160 },
    smoothTargetRatio: 1,
    target: "warp.source",
    userFacingRange: "fully-guaranteed",
  },
} as const;
const fourKIntrinsicMedia = {
  kind: "media",
  reason: "A 3840×2160 photo at Warp's source-native default Resolution scale 1 is the realistic intrinsic import baseline.",
  value: { width: 3840, height: 2160 },
  loadProfile: {
    hardLimit: { width: 3840, height: 2160 },
    metric: "media-area",
    smoothTarget: { width: 3840, height: 2160 },
    smoothTargetRatio: 1,
    target: "warp.source",
    userFacingRange: "fully-guaranteed",
  },
} as const;

function responsive(id: string, target: string, controlLabel: string, interaction: "control-change" | "control-drag" = "control-change") {
  return {
    automated: true,
    automatedTestName: `perf: ${target} remains responsive`,
    browser: true,
    browserTestName: `browser perf: ${target} remains responsive`,
    budget: commonBudget,
    controlLabel,
    expectedObservable: `${controlLabel} updates Radial Warp pixels without moving the canvas viewport or re-decoding the source.`,
    fixture: "4K photographic source with Resolution scale 2.",
    id,
    interaction,
    target,
    workload: false,
  } as const;
}

export const warpPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    preferredRunner: "agent-browser",
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
  },
  rendererStrategy: "webgl",
  rendererWorkload: "pixel-output",
  rendererTechnique: {
    sourceRepresentation: "image-media",
    productRepresentation: "pixel",
    previewRenderer: "webgl",
    exportRenderer: "webgl",
    rendererWorkload: "pixel-output",
    rendererStrategy: "webgl",
    fidelityRisks: ["Sparse uniform zoom samples can appear as repeated layers; fixed stratified jitter distributes six samples continuously across the exposure while post-accumulation contrast preserves photographic density."],
    performanceRisks: ["8K export combines a 8192px long edge with a stable six-sample long-exposure kernel and remains an export-only workload."],
    whyNotAlternativeStrategies: [
      "Canvas 2D would run high-resolution straight-path sampling and smoothing on the main thread.",
      "SVG and DOM cannot represent arbitrary photographic pixel resampling.",
      "WebGPU would add compatibility and setup cost without improving this single-texture, single-pass fragment workload enough to justify a second path.",
    ],
    layers: [
      { id: "background", kind: "background", renderer: "webgl", primitiveCount: "low", content: ["composite"], exportMode: "composited", uiSelector: "[data-toolcraft-product-output]" },
      { id: "warp", kind: "product-foreground", renderer: "webgl", primitiveCount: "high", content: ["bitmap-media", "shader"], exportMode: "included", uiSelector: "[data-toolcraft-product-output]" },
      { id: "focus-handle", kind: "editing-handles", renderer: "dom", primitiveCount: "low", content: ["geometry"], exportMode: "excluded", uiSelector: "[data-warp-focus-handle]" },
      { id: "still-export", kind: "export-composite", renderer: "webgl", primitiveCount: "high", content: ["bitmap-media", "composite"], exportMode: "composited" },
    ],
  },
  rendererPipeline: {
    passes: [
      { id: "source-decode", kind: "decode", runsOn: "main", output: "source", quality: "full", inputs: ["warp.source", "mediaAssets[].transform"], invalidatedBy: ["warp.source", "mediaAssets[].transform"], cacheKey: ["warp.source.dataUrl", "mediaAssets[].transform"] },
      { id: "texture-upload", kind: "preprocess", runsOn: "gpu", output: "intermediate", quality: "full", inputs: ["source-decode"], invalidatedBy: ["source-decode"], cacheKey: ["warp.source.dataUrl", "mediaAssets[].transform"] },
      { id: "radial-warp", kind: "pixel-transform", runsOn: "gpu", output: "preview", quality: "retina", inputs: ["texture-upload", "warp.focus", "warp.strength", "warp.softness", "warp.falloff", "warp.blend", "canvas.size", "canvas.renderScale", "warp.background", "export.includeBackground"], invalidatedBy: ["texture-upload", "warp.focus", "warp.strength", "warp.softness", "warp.falloff", "warp.blend", "canvas.size", "canvas.renderScale", "warp.background", "export.includeBackground"], cacheKey: ["warp.source.dataUrl", "mediaAssets[].transform"] },
      { id: "focus-handle", kind: "composite", runsOn: "main", output: "overlay", quality: "full", inputs: ["warp.focus"], invalidatedBy: ["warp.focus"], cacheKey: ["warp.focus"] },
      { id: "still-export", kind: "export", runsOn: "export-only", output: "export", quality: "export", inputs: ["texture-upload", "radial-warp", "export.image.format", "export.image.resolution", "warp.exportAction"], invalidatedBy: ["radial-warp", "export.image.format", "export.image.resolution", "warp.exportAction"], cacheKey: ["warp.source.dataUrl", "mediaAssets[].transform", "warp.focus", "warp.strength", "warp.softness", "warp.falloff", "warp.blend"] },
    ],
    interactionInvalidation: [
      { interaction: "media-import", targets: ["warp.source"], invalidates: ["source-decode", "texture-upload", "radial-warp"], mustNotInvalidate: ["still-export"] },
      { interaction: "control-drag", targets: ["warp.strength", "warp.softness", "warp.falloff", "warp.blend"], invalidates: ["radial-warp"], mustNotInvalidate: ["source-decode", "texture-upload", "still-export"] },
      { interaction: "control-change", targets: ["warp.focus", "export.includeBackground", "warp.background", "export.image.format", "export.image.resolution", "warp.exportAction"], invalidates: ["radial-warp", "focus-handle"], mustNotInvalidate: ["source-decode", "texture-upload"] },
      { interaction: "mask-drag", targets: ["warp.focus"], invalidates: ["radial-warp", "focus-handle"], mustNotInvalidate: ["source-decode", "texture-upload", "still-export"] },
      { interaction: "viewport-drag", targets: ["canvas.viewport"], invalidates: [], mustNotInvalidate: ["source-decode", "texture-upload", "radial-warp", "still-export"] },
      { interaction: "viewport-zoom", targets: ["canvas.zoom"], invalidates: [], mustNotInvalidate: ["source-decode", "texture-upload", "radial-warp", "still-export"] },
      { interaction: "export", targets: ["export.image.resolution", "warp.exportAction"], invalidates: ["still-export"], mustNotInvalidate: ["source-decode", "texture-upload"] },
    ],
  },
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: warp source media import is covered",
      browser: true,
      browserTestName: "browser perf: warp source media import is covered",
      budget: { maxFrameGapMs: 400, maxInteractionMs: 1200, maxLongTaskMs: 400 },
      controlLabel: "Image",
      expectedObservable: "A 4K source decodes and uploads once before the GPU warp preview renders.",
      fixture: "3840×2160 photographic source.",
      id: "source-import",
      interaction: "media-import",
      stressFixture: fourKIntrinsicMedia,
      target: "warp.source",
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: Warp strength maximum stays responsive",
      browser: true,
      browserTestName: "browser perf: warp strength maximum stays responsive",
      budget: { maxFrameGapMs: 180, maxInteractionMs: 1200, maxLongTaskMs: 180 },
      controlLabel: "Motion",
      expectedObservable: "The live 4K-class preview reaches maximum solid radial pixel-stretch length in one stable shader pass.",
      fixture: "4K photographic source with Resolution scale 2.",
      id: "strength-max",
      interaction: "control-drag",
      stressFixture: { kind: "max-value", reason: "100% is the exposed maximum radial image-strip stretch.", value: 100, loadProfile: { hardLimit: 100, metric: "count", smoothTarget: 100, smoothTargetRatio: 1, target: "warp.strength", userFacingRange: "fully-guaranteed" } },
      workloadFixture: fourKMedia,
      target: "warp.strength",
      values: { min: 0, default: 64, max: 100 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: export.image.resolution workload is covered",
      browser: true,
      browserTestName: "browser perf: export.image.resolution workload is covered",
      budget: { maxExportMs: 8000 },
      controlLabel: "Resolution",
      expectedObservable: "The selected 8K long edge is rendered through the same shader and encoded without changing preview resolution.",
      fixture: "4K photographic source with maximum stretch and 8K export selected.",
      id: "image-resolution",
      interaction: "control-change",
      stressFixture: { kind: "max-value", reason: "8K is the maximum exposed still resolution.", value: "8k" },
      workloadFixture: fourKMedia,
      target: "export.image.resolution",
      values: { min: "2k", default: "4k", max: "8k" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: warp export action is covered",
      browser: true,
      browserTestName: "browser perf: warp export action is covered",
      budget: { maxExportMs: 8000 },
      controlLabel: "Export PNG",
      expectedObservable: "The sticky action downloads selected-format full-resolution Warp pixels with progress.",
      fixture: "4K photographic source with maximum stretch and 8K output available.",
      id: "export-action",
      interaction: "export-copy",
      stressFixture: { kind: "max-value", reason: "Full-resolution image export is the action's heaviest path.", value: "export-warp-image" },
      workloadFixture: fourKMedia,
      target: "warp.exportAction",
      workload: true,
    },
    responsive("focus", "warp.focus", "Position"),
    responsive("strength", "warp.strength", "Motion", "control-drag"),
    responsive("softness", "warp.softness", "Exposure", "control-drag"),
    responsive("falloff", "warp.falloff", "Focus area", "control-drag"),
    responsive("blend", "warp.blend", "Blend", "control-drag"),
    responsive("background-include", "export.includeBackground", "Include"),
    responsive("background-color", "warp.background", "Background"),
    responsive("image-format", "export.image.format", "Format"),
    {
      automated: true,
      automatedTestName: "perf: Radial Warp maximum preview stays under budget",
      browser: true,
      browserTestName: "browser perf: radial warp maximum preview stays under budget",
      budget: { maxPreviewMs: 1800, maxLongTaskMs: 180 },
      expectedObservable: "The 4K/2× preview renders one stable stratified long-exposure frame with one cached source texture.",
      fixture: "4K photo, Motion 100, Exposure 100, Resolution scale 2.",
      id: "preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: { kind: "custom", reason: "This is the combined worst-case live preview state.", value: { sourceMedia: { width: 3840, height: 2160 }, softness: 100, strength: 100, renderScale: 2 }, loadProfile: { hardLimit: { sourceMedia: { width: 3840, height: 2160 }, softness: 100, strength: 100, renderScale: 2 }, metric: "custom", smoothTarget: { sourceMedia: { width: 3840, height: 2160 }, softness: 100, strength: 100, renderScale: 2 }, smoothTargetRatio: 1, target: "warp.preview", userFacingRange: "fully-guaranteed" } },
      uiSelector: "[data-toolcraft-product-output]",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Radial Warp viewport zoom stays stable",
      browser: true,
      browserTestName: "browser perf: radial warp viewport zoom stays stable",
      budget: commonBudget,
      expectedObservable: "Toolbar zoom preserves the maximum GPU preview and its cached source texture.",
      fixture: "Maximum Warp preview state.",
      id: "viewport-zoom",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: { kind: "custom", reason: "Zoom must hold the combined maximum preview state.", value: { sourceMedia: { width: 3840, height: 2160 }, softness: 100, strength: 100, renderScale: 2 }, loadProfile: { hardLimit: { sourceMedia: { width: 3840, height: 2160 }, softness: 100, strength: 100, renderScale: 2 }, metric: "custom", smoothTarget: { sourceMedia: { width: 3840, height: 2160 }, softness: 100, strength: 100, renderScale: 2 }, smoothTargetRatio: 1, target: "canvas.zoom", userFacingRange: "fully-guaranteed" } },
      target: "canvas.zoom",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: ["warp.source", "export.image.resolution", "warp.exportAction"],
});
